ci(gitlab): test early skip (2)

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -37,33 +37,30 @@ Data fetch:
     - git remote set-url origin https://${GITHUB_TOKEN}@github.com/${CI_PROJECT_PATH}.git
     - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
   script:
-    - echo -e "\n" >> ./data/index.json
+    - echo -e "\n" >> ./data/index.json3
+
     - |
-      if [[ ! -n "$(git status -s ./data)" ]]; then
+      if [[ "$(git status -s ./data)" ]]; then
         echo "Nothing changed"
         exit ${CI_JOB_SKIP_EXIT_CODE:-0}"
       fi
+
     - |
-      if [[ -n "$(git status -s ./data)" ]]; then
-        echo "Files changed, checking JSON validity"
-        # Check JSON files
-        for filename in ./data/LEGITEXT*\.json; do
-          node -e "assert(require('$filename').children.length > 0)" || {
-            echo "Invalid JSON in $filename : should have children"
-            exit 1
-          }
-        done
+      echo "Files changed, checking JSON validity"
+      # Check JSON files
+      for filename in ./data/LEGITEXT*\.json; do
+        node -e "assert(require('$filename').children.length > 0)" || {
+          echo "Invalid JSON in $filename : should have children"
+          exit 1
+        }
+      done
 
-        echo "Commit files"
-        # Commit files
-        NOW=$(date +"%Y%m%d_%H%M")
-        git add data
-        git commit -m "feat(data): $NOW update"
-        git push --no-verify origin HEAD:${CI_COMMIT_REF_NAME}
+      echo "Commit files"
+      # Commit files
+      NOW=$(date +"%Y%m%d_%H%M")
+      git add data
+      git commit -m "feat(data): $NOW update"
+      git push --no-verify origin HEAD:${CI_COMMIT_REF_NAME}
 
-        yarn global add semantic-release @semantic-release/git @semantic-release/exec
-        $(yarn global bin)/semantic-release
-
-      else
-        echo "Nothing changed"
-      fi
+      yarn global add semantic-release @semantic-release/git @semantic-release/exec
+      $(yarn global bin)/semantic-release
